import PageHeader from "@/components/PageHeader";

const SECTIONS = [
  {
    title: "1. Use of the Service",
    body: [
      "You may use this service to build a personal portfolio presence and to create, edit, and export CV/resume documents. You agree to provide accurate information and to use the service only for lawful purposes.",
    ],
  },
  {
    title: "2. Account Responsibility",
    body: [
      "You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account. Notify us immediately if you suspect unauthorized access.",
    ],
  },
  {
    title: "3. Your Content",
    body: [
      "You retain ownership of the information and content you enter into the CV Maker (personal details, work history, education, etc.). By using the AI-assisted writing feature, you understand that suggested text is generated by a third-party AI model (Google Gemini) based on the information you provide, and you are responsible for reviewing all AI-generated content for accuracy before use, particularly for formal applications such as university admissions or visa submissions.",
    ],
  },
  {
    title: "4. AI-Generated Content Disclaimer",
    body: [
      "AI-generated summaries and descriptions are provided as drafting assistance only. We do not guarantee the accuracy, completeness, or suitability of AI-generated content for any specific purpose, including but not limited to visa or university applications. You are solely responsible for reviewing and verifying all content before submission to any third party.",
    ],
  },
  {
    title: "5. Service Availability",
    body: [
      'This service is provided on an "as is" and "as available" basis. We do not guarantee uninterrupted or error-free operation and may modify, suspend, or discontinue the service at any time.',
    ],
  },
  {
    title: "6. Limitation of Liability",
    body: [
      "To the fullest extent permitted by law, we are not liable for any indirect, incidental, or consequential damages arising from your use of this service, including any decisions made based on AI-generated content.",
    ],
  },
  {
    title: "7. Third-Party Services",
    body: [
      "This service integrates with third-party providers (Google, Meta/Facebook, Resend, Render, Neon, Cloudflare) as described in our Privacy Policy. Your use of features involving these providers is also subject to their respective terms.",
    ],
  },
  {
    title: "8. Termination",
    body: ["We may suspend or terminate your access to the service if you violate these Terms."],
  },
  {
    title: "9. Changes to These Terms",
    body: [
      "We may update these Terms from time to time. Continued use of the service after changes constitutes acceptance of the updated Terms.",
    ],
  },
  {
    title: "10. Contact",
    body: ["Questions about these Terms can be directed to: amangupta00121212@gmail.com"],
  },
];

export default function TermsOfServicePage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-20">
      <PageHeader eyebrow="Legal" title="Terms of Service" description="Last updated: August 2026" />

      <p className="text-base leading-relaxed text-foreground/80">
        These Terms of Service (&ldquo;Terms&rdquo;) govern your use of this website and the CV Maker tool,
        operated by Aman Rauniyar (&ldquo;we,&rdquo; &ldquo;us,&rdquo; &ldquo;our&rdquo;). By using this
        service, you agree to these Terms.
      </p>

      <div className="mt-10 space-y-10">
        {SECTIONS.map((section) => (
          <section key={section.title}>
            <h2 className="text-xl font-semibold text-foreground">{section.title}</h2>
            <div className="mt-3 space-y-4">
              {section.body.map((paragraph) => (
                <p key={paragraph} className="text-base leading-relaxed text-foreground/80">
                  {paragraph}
                </p>
              ))}
            </div>
          </section>
        ))}
      </div>
    </main>
  );
}
