// Nepalese first (the default), then the rest alphabetically.
export const NATIONALITIES: string[] = [
  "Nepalese",
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Argentine",
  "Australian",
  "Austrian",
  "Bangladeshi",
  "Belgian",
  "Bhutanese",
  "Brazilian",
  "British",
  "Burmese",
  "Canadian",
  "Chinese",
  "Danish",
  "Dutch",
  "Egyptian",
  "Emirati",
  "Filipino",
  "Finnish",
  "French",
  "German",
  "Greek",
  "Hungarian",
  "Icelandic",
  "Indian",
  "Indonesian",
  "Irish",
  "Israeli",
  "Italian",
  "Japanese",
  "Kuwaiti",
  "Malaysian",
  "Maldivian",
  "Mexican",
  "New Zealander",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Polish",
  "Portuguese",
  "Qatari",
  "Russian",
  "Saudi Arabian",
  "Singaporean",
  "South African",
  "South Korean",
  "Spanish",
  "Sri Lankan",
  "Swedish",
  "Swiss",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Vietnamese",
];
